# Generated by Django 5.2 on 2025-04-14 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_last_updated_by_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('Not Viewed', 'Not Viewed'), ('Viewed', 'Viewed')], default='Not Viewed', max_length=20),
        ),
    ]
